<font class="pageFoot"><!-- Questions or Comments?  -->
<script language="JavaScript">
<!--
// var name = "tmayer";
// var domain = "personnel.com";
// document.write('<a href=\"mailto:' + name + '@' + domain + '\">');
// document.write('E-mail' + '&nbsp;' + 'Personnel' + '&nbsp;' + 'Plus' + '</a>');
// -->
</script>
<!-- <br> -->
&copy; <SCRIPT LANGUAGE="JavaScript">
<!--
    tday=new Date();
    yr0=tday.getFullYear();

  // end hiding -->
</SCRIPT>
<SCRIPT LANGUAGE="JavaScript">
  <!-- Hide from old browsers
    document.write(yr0);
  // end hiding -->
</SCRIPT> Personnel Plus, Inc. All Rights Reserved.</font>
</div>