<HTML> 
<BODY BGCOLOR="#FFFFFF"> 
<FORM METHOD="POST" ENCTYPE="multipart/form-data" ACTION="UploadScript3.asp"> 
<INPUT TYPE=FILE SIZE=60 NAME="FILE1"><BR> 
<INPUT TYPE=FILE SIZE=60 NAME="FILE2"><BR> 
<INPUT TYPE=FILE SIZE=60 NAME="FILE3"><BR> 
<INPUT TYPE=SUBMIT VALUE="Upload!">
</FORM>
</BODY> 
</HTML>