if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[openwiki_config]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[openwiki_config]
GO

CREATE TABLE [dbo].[openwiki_config] (
	[pk_ow] [int] IDENTITY (1, 1) PRIMARY KEY NOT NULL ,
	[ow_version] [varchar] (50) NOT NULL DEFAULT ('1.0'),
	[ow_buildnumber] [varchar] (50) NOT NULL DEFAULT ('20040101'),
	[ow_imagepath] [varchar] (255) NOT NULL DEFAULT ('ow/images'),
	[ow_iconpath] [varchar] (255) NOT NULL DEFAULT ('ow/images/icons') ,
	[ow_encoding] [varchar] (50) NOT NULL DEFAULT ('ISO-8859-1') ,
	[ow_title] [varchar] (255) NOT NULL DEFAULT ('OpenWiki 2004') ,
	[ow_frontpage] [varchar] (255) NOT NULL DEFAULT ('FrontPage') ,
	[ow_welcomepage] [varchar] (255) NOT NULL DEFAULT ('FrontPage') ,
	[ow_scriptname] [varchar] (50) NOT NULL DEFAULT ('ow.asp') ,
	[ow_maxtext] [int] NOT NULL DEFAULT (204800),
	[ow_maxincludelevel] [int] NOT NULL DEFAULT (5) ,
	[ow_rcname] [varchar] (255) NOT NULL DEFAULT ('RecentChanges') ,
	[ow_rcdays] [int] NOT NULL DEFAULT (30),
	[ow_maxtrail] [int] NOT NULL DEFAULT (5) ,
	[ow_stopwords] [varchar] (255) NOT NULL DEFAULT ('StopWords') ,
	[ow_templates] [varchar] (255) NOT NULL DEFAULT ('Template$') ,
	[ow_timezone] [varchar] (255) NOT NULL DEFAULT ('+01:00') ,
	[ow_maxnrofaggr] [int] NOT NULL DEFAULT (150) ,
	[ow_maxwebgets] [int] NOT NULL DEFAULT (3) ,
	[ow_scripttimeout] [int] NOT NULL DEFAULT (120) ,
	[ow_daystokeep] [int] NOT NULL DEFAULT (30) ,
	[ow_uploaddir] [varchar] (255) NOT NULL DEFAULT ('attachments/') ,
	[ow_maxuploadsize] [bigint] NOT NULL DEFAULT (8388608) ,
	[ow_uploadtimeout] [int] NOT NULL DEFAULT (300) ,
	[ow_activeskin] [varchar] (255) NOT NULL DEFAULT ('') ,
	[ow_msxml_version] [int] NOT NULL DEFAULT (3) ,
	[ow_readpassword] [varchar] (50) NOT NULL DEFAULT ('') ,
	[ow_editpassword] [varchar] (50) NOT NULL DEFAULT ('') ,
	[ow_adminpassword] [varchar] (50) NOT NULL DEFAULT ('adminpw') ,
	[ow_defaultbookmarks] [varchar] (255) NOT NULL DEFAULT (' RecentChanges TitleIndex UserPreferences RandomPage Help') ,
	[ow_writehtml] [bit] NOT NULL DEFAULT (0),
	[ow_readonly] [bit] NOT NULL DEFAULT (0) ,
	[ow_nakedview] [bit] NOT NULL DEFAULT (0) ,
	[ow_usesubpage] [bit] NOT NULL DEFAULT (1) ,
	[ow_freelinks] [bit] NOT NULL DEFAULT (1) ,
	[ow_wikilinks] [bit] NOT NULL DEFAULT (1) ,
	[ow_acronymlinks] [bit] NOT NULL DEFAULT (0) ,
	[ow_templatelinking] [bit] NOT NULL DEFAULT (1) ,
	[ow_rawhtml] [bit] NOT NULL DEFAULT (0) ,
	[ow_mathml] [bit] NOT NULL DEFAULT (0) ,
	[ow_cachexsl] [bit] NOT NULL DEFAULT (0) ,
	[ow_cachexml] [bit] NOT NULL DEFAULT (0) ,
	[ow_allowrssexport] [bit] NOT NULL DEFAULT (1) ,
	[ow_allownewsyndications] [bit] NOT NULL DEFAULT (1) ,
	[ow_allowaggregations] [bit] NOT NULL DEFAULT (1) ,
	[ow_embeddedmode] [bit] NOT NULL DEFAULT (0) ,
	[ow_allowattachments] [bit] NOT NULL DEFAULT (0) ,
	[ow_simplelinks] [bit] NOT NULL DEFAULT (1) ,
	[ow_nonenglish] [bit] NOT NULL DEFAULT (1) ,
	[ow_networkfile] [bit] NOT NULL DEFAULT (0) ,
	[ow_brackettext] [bit] NOT NULL DEFAULT (1) ,
	[ow_htmllinks] [bit] NOT NULL DEFAULT (1) ,
	[ow_bracketwiki] [bit] NOT NULL DEFAULT (1) ,
	[ow_showbrackets] [bit] NOT NULL DEFAULT (0) ,
	[ow_freeupper] [bit] NOT NULL DEFAULT (1) ,
	[ow_linkimages] [bit] NOT NULL DEFAULT (1) ,
	[ow_useheadings] [bit] NOT NULL DEFAULT (1) ,
	[ow_uselookup] [bit] NOT NULL DEFAULT (1) ,
	[ow_stripntdomain] [bit] NOT NULL DEFAULT (1) ,
	[ow_maskipaddress] [bit] NOT NULL DEFAULT (1) ,
	[ow_oldskool] [bit] NOT NULL DEFAULT (1) ,
	[ow_newskool] [bit] NOT NULL DEFAULT (1) ,
	[ow_numtoc] [bit] NOT NULL DEFAULT (0) ,
	[ow_ntauthentication] [bit] NOT NULL DEFAULT (1) ,
	[ow_directedit] [bit] NOT NULL DEFAULT (1) ,
	[ow_allowcharrefs] [bit] NOT NULL DEFAULT (1) ,
	[ow_wikifyheaders] [bit] NOT NULL DEFAULT (0) ,
	[ow_emoticons] [bit] NOT NULL DEFAULT (1) ,
	[ow_uselinkicons] [bit] NOT NULL DEFAULT (0) ,
	[ow_prettylinks] [bit] NOT NULL DEFAULT (1) ,
	[ow_externalout] [bit] NOT NULL DEFAULT (1) 
) ON [PRIMARY]
GO

