<!-- #INCLUDE VIRTUAL='/include/master/html_header.asp' -->
<%
Session("additionalStyling") = "general.asp.css" %>
<!-- #INCLUDE VIRTUAL='/include/master/html_styles.asp' -->
<!-- Revision Date: 2009.07.25 -->
<!-- #INCLUDE VIRTUAL='/include/master/navi_top_menu.asp' -->
  <%=decorateTop("", "", "Privacy Policy")%>
  <div id="privacyPolicy">
    <h2><span>Our Committment to Privacy Protection</span></h2>
    <p>Personnel Plus, Inc. (here forth referred to as Personnel Plus) is committed to protecting the privacy of our users. We want to provide a safe, secure user experience. We will use our best efforts to ensure that the information you submit to us remains private, and is used only for the purposes as set forth herein. The following reflects our commitment to you.</p>
    <h2><span>General Collected Information</span></h2>
    <p>In general, we gather information about all of our users collectively, such as what areas users visit most frequently and what services users access the most. We only use such data anonymously and in the aggregate. We also collect an IP (Internet Protocol) address from all visitors to our site. We use your IP address to help diagnose problems with our server, and to administer our site. Your IP address is also used to help identify you when you visit and keep your information secure. This information helps us determine what is most beneficial for our users, and how we can continually create a better overall experience for you. We may share this information with our partners, but only in the aggregate, so that they too may understand how Personnel Plus visitors use our site, so they may create a better overall experience for you, as well.</p>
    <h2><span>User Information</span></h2>
    <p>When you register for the services provided on this site, you will be asked to provide Personnel Plus with certain information including, without limitation, a valid e&#45;mail address, name, address, telephone number, interests, etc. In addition to the terms and conditions that may be set forth in any legal policy on this Web site, you understand and agree that Personnel Plus may disclose to third parties, on an anonymous basis, certain aggregate information contained in your registration application. Personnel Plus will not disclose to any third party your name, address, e-mail address, or telephone number without your prior consent, except to the extent necessary or appropriate to comply with applicable laws or in legal proceedings where such information is relevant.</p>
    <p>With prior permission, we may use the provided information to make you aware of additional products and services that may be of interest to you or to contact you regarding site changes. Personnel Plus also reserves the right to offer third party services and products to you based on the preferences that you identified in your registration and at any time thereafter; such offers may be made by Personnel Plus or by third parties. Personnel Plus also provides you with the opportunity to opt-out of these types of communications. If you choose to receive these types of communications at the time of registration or at any time thereafter, but later decide you no longer want to receive them, simply follow the instructions in the email to opt-out or follow instructions in the online help.</p>
    <p>All users should be aware that when they voluntarily display or distribute personal information, that information may be collected and used by others. This may result in unsolicited messages form third parties, for which Personnel Plus is not responsible.</p>
    <p>We employ other companies and individuals to perform functions on our behalf. Examples may include hosting our web servers, analyzing data, providing marketing assistance, processing credit card payments, and providing customer service. These other companies will have access to your personal information as necessary to perform their functions, but they may not share that information with any third party.</p>
    <h2><span>Resumes</span></h2>
    <p>Since Personnel Plus contains services for job finders (&quot;Members&quot;) to submit online resumes to potential employers, the resume information will be saved in our database. Your resume may be &quot;activated&quot; as searchable or &quot;deactivated&quot; for private job applying. The two options are:</p>
    <p>When you build a resume online you may leave it in our database as &quot;deactivated&quot; which will not allow it to be searchable by potential employers. Not allowing your resume to be searchable means that you can use it to apply for a job online, but employers and recruiters will not have access to search it through our resume database product.</p>
    <p>By &quot;activating&quot; your online resume you allow your resume to be searchable, then all employers and recruiters who pay for access to our resume database product will have access to your resume.</p>
    <p>We use our best efforts to grant access to this database only to paying employers, recruiters, hiring managers, headhunters, and human resource professionals, but cannot guarantee that other parties will not, without our consent, gain access to this database. You may remove your resume from our searchable database at any time. However, employers and recruiters who have paid for access to the database, and other parties who have otherwise gained access to the database, may have retained a copy of your resume in their own files or databases. We are not responsible for the retention, use, or privacy of resumes in these instances, or for the use or privacy of resumes by any of such parties while resumes are in the database.</p>
    <h2><span>Updating Account Information</span></h2>
    <p>Personnel Plus allows you to change, correct or remove your personal information at any time. To do so, simply log in to your account, go to your account options, and you will find options for editing the information you have submitted. Please keep this information accurate and up-to-date if possible.</p>
    <h2><span>Cookies</span></h2>
    <p>To enhance your experience at Personnel Plus, we use a feature on your Internet browser called a "cookie". Cookies are small files that your Web browser places on your computer's hard drive. We use cookies for remembering user names and passwords and preferences, tracking click streams, and for load balancing. Because of our use of cookies, we can deliver faster service, consistent, updated results, and a more personalized site experience. You have the option of setting your browser to reject cookies. However, doing this will hinder performance and negatively impact your experience on our site.</p>
    <h2><span>Children</span></h2>
    <p>We do not specifically collect information about children. We believe that children should get their parents' consent before giving out personal information.</p>
    <h2><span>Privacy Commitment Changes</span></h2>
    <p>If we decide to change our privacy commitment for PersonnelPlus-Inc.com, we will post those changes here so that you will always know what information we gather, how we might use that information, and whether we will disclose it to anyone. If, at any time, you have questions or concerns about PersonnelPlus-Inc.com privacy commitment, please feel free to contact us.</p>
    <a name="terms"></a>
    <h2><span>Legal Notice</span></h2>
    <p>THE TERMS, CONDITIONS AND NOTICES BELOW WILL GOVERN YOUR USE OF THE PERSONNEL PLUS SYSTEM. THEY ALSO PROVIDE NOTICE OF SOME OF PERSONNEL PLUS'S POLICIES. PLEASE READ THEM CAREFULLY!</p>
    <blockquote>
      <p>The PersonnelPlus-Inc.com System, as well as other related System's, are offered to you, the user, only conditioned on your acceptance without modification of the terms, conditions and notices contained herein. &quot;System&quot; also refers to all information, text and visual images, software, products and services used or available via the System. Any and all rights not expressly granted in these Terms, Conditions and Notices (collectively, these &quot;Terms&quot;) are reserved by PersonnelPlus-Inc.com. PersonnelPlus-Inc.com reserves the right to change these Terms, at its sole discretion, at any time or from time to time. Your use of the System means that you&#146;ve read all of these Terms and agree to them. For further information relating to the legal issues contained in these Terms or problem reports regarding this service, please contact us.</p>
      <h2><span>General: Trademarks, Copyrights, etc.</span></h2>
      <p>PersonnelPlus-Inc.com (&quot;PersonnelPlus-Inc.com&quot;) is the owner of all intellectual property rights (including copyrights) in the PersonnelPlus-Inc.com System. Material published by PersonnelPlus-Inc.com on this System may contain other proprietary notices or describe products, services, processes or technologies owned by PersonnelPlus-Inc.com or third parties. Nothing in these Terms or in the System shall be construed as granting to you a license under any copyright, trademark, patent or other intellectual property right of PersonnelPlus-Inc.com or any third party, except as expressly set forth herein.</p>
      <p>All other product and service marks contained herein are the trademarks of their respective owners. The &quot;look&quot; and &quot;feel&quot; of PersonnelPlus-Inc.com&#146;s site (including color combinations, button shapes, layout, design and all other graphical elements) are also PersonnelPlus-Inc.com&#146;s trademarks or copyrights. All editorial content and graphics on this site, as well as the HTML based computer programs used to generate pages, and the Web site are protected by U.S. copyright laws and international treaties and may not be copied without the express permission of PersonnelPlus-Inc.com, which reserves all rights. Re-use of any of PersonnelPlus-Inc.com's editorial content and graphics for any purpose is strictly prohibited without PersonnelPlus-Inc.com&#146;s prior written permission.</p>
      <p>Please be aware that the information, software, products and services published on this System may include inaccuracies, typographical errors or out-of-date information. Changes are made and items added to the System and the information on it from time to time. PersonnelPlus-Inc.com may make such changes or additions at any time at its sole discretion.</p>
      <h2><span>Other Parties.</span></h2>
      <p>This System may contain hyperlinks or other connections to Web sites operated by parties other than PersonnelPlus-Inc.com, including but not limited to those of the PersonnelPlus-Inc.com Member companies and agencies or its advertisers (individually or collectively, as the case may be, &quot;Members&quot;). PersonnelPlus-Inc.com does not control these Web sites and is not responsible for them, including for their availability, content or any viruses accessed through them. PersonnelPlus-Inc.com&#146; inclusion of hyperlinks or other connections to such Web sites does not imply any endorsement of the material on them or any association with their owners or operators. PersonnelPlus-Inc.com takes no responsibility whatsoever for the activities of job applicants or PersonnelPlus-Inc.com Members or those Members&#146; respective hiring, recruiting or other practices (or any of the information posted or downloaded by them on the System). Nothing on the System shall be deemed to be an endorsement, representation or warranty with respect to any Member, applicant or other third party, whether in regard to its Web site, products, services or otherwise.</p>
      <h2><span>Your Use; Limited License.</span></h2>
      <p>The PersonnelPlus-Inc.com System is for your personal and noncommercial use. Except as otherwise expressly provided, you may not modify, copy, distribute, transmit, display, perform, reproduce, use, publish, license, create derivative works from, transfer or sell any information or content contained in the System, the PersonnelPlus-Inc.com Web site as a whole software, products or services obtained from or available as part of or in conjunction with this System. You are granted a non-exclusive, non-assignable and non-transferable license to use the System only under these terms and conditions of use. This license is not a sale of any of the owner's rights. The PersonnelPlus-Inc.com System may be used only by you, and you may not rent, lease, lend, sub-license or transfer the System or any data residing on it or any of your rights under this agreement to anyone else. You may not develop or derive for commercial sale any data in machine-readable or other form that incorporates or uses any substantial part of the System. You may not transfer to or store any data residing or exchanged over the PersonnelPlus-Inc.com System in any electronic network for use by more than one user unless you obtain prior written permission from PersonnelPlus-Inc.com.</p>
      <h2><span>Your Responsibilities.</span></h2>
      <p>The PersonnelPlus-Inc.com Site may be used only for lawful purposes by individuals seeking employment and employers seeking employees. As one of the conditions of your use of the PersonnelPlus-Inc.com System, you represent, warrant and agree that you will not use (or plan, encourage or help others to use) the System for any purpose or in any manner that is prohibited by these terms, conditions and notices or by applicable law (including but not limited to any applicable export controls). It is YOUR RESPONSIBILITY to ensure that your use of the System complies with these terms, conditions and notices and to seek prior written permission from PersonnelPlus-Inc.com for any uses not permitted or not expressly specified herein.</p>
      <h2><span>In connection with your use of our System, you will not:</span></h2>
      <p>1. Transmit any message, information, data, text, software or images, or other materials (&quot;Content&quot;) that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, hateful, racially, ethnically or otherwise objectionable that may invade another's right of privacy or publicity;</p>
      <p>2. Impersonate any person or entity, including but not limited to, a PersonnelPlus-Inc.com official, forum leader, guide or host or falsely state or otherwise misrepresent your affiliation with a person or entity;</p>
      <p>3. Post or transmit any Content that you do not have a right to reproduce, display or transmit under any law or under contractual or fiduciary relationships (such as nondisclosure agreements);</p>
      <p>4. Post or transmit any Content that contains a virus or corrupted data;</p>
      <p>5. Delete any author attributions, legal notices or proprietary designations or labels that you upload to any communication feature;</p>
      <p>6. Use the Site&#146;s communication features in a manner that adversely affects the availability of its resources to other users (e.g., excessive shouting, use of all caps, or flooding continuous posting of repetitive text);</p>
      <p>7. Post or transmit any unsolicited advertising, promotional materials, &quot;chain letters&quot;, &quot;spam&quot;, &quot;junk mail&quot;, &quot;pyramid schemes&quot; or any other form of solicitation or any non-resume information such as opinions or notices, commercial or otherwise;</p>
      <p>8. Violate any applicable local, state, national or international law; and;</p>
      <p>9. Upload or transmit any Content that infringes any patent, trademark, trade secret, copyright or other proprietary rights (&quot;Rights&quot;) of any party.</p>
      <p>&nbsp; &nbsp; &nbsp; a. Post any incomplete, false or inaccurate resume information or information which is not your own accurate resume (living individual seeking employment on a full-time or part-time basis on his or her own behalf).</p>
      <p>&nbsp; &nbsp; &nbsp; b. Respond to any employment opportunity on the System for any reason other than to apply for the job. Communications soliciting the employer's business by our competitors are prohibited.</p>
      <p>12. Post to the System any franchise, pyramid scheme, &quot;club membership&quot;, distributorship or sales representative agency arrangement or other business opportunity which requires an up front or periodic payment, pays commissions only (no significant salary), requires recruitment of other members, sub-distributors or sub-agents.</p>
      <p>13. Delete or revise any material posted by any other person or entity.</p>
      <p>14. Print out or otherwise copy or use any personally identifiable information about employees or business information about employers. Unsolicited e-mail, telephone calls, mailings or other contacts to posting individuals and companies are prohibited.</p>
      <h2><span>Web Site Security Rules.</span></h2>
      <p>Users are prohibited from violating or attempting to violate the security of PersonnelPlus-Inc.com, including, without limitation, (1) accessing data not intended for such user or logging into a server or account which such user is Account not associated and or Not Authorized, please contact 1 (877) 733-7300 or email accounts@personnel.com to access, (2) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization,(3) attempting to interfere with service to any user, host or network, including, without limitation, via means of overloading, &quot;mailbombing&quot;, or &quot;crashing&quot;, &quot;flooding&quot; or (4)sending unsolicited e-mail, including promotions or advertising of products or services, or (5) forging any TCP/IP packet header or any part of the header information in any e-mail or newsgroup posting. Violations of System or network security may result in civil or criminal liability. PersonnelPlus-Inc.com will investigate occurrences which may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations.</p>
      <h2><span>Your Grants.</span></h2>
      <p>By submitting (e.g., uploading) Content to the System, you automatically grant PersonnelPlus-Inc.com the royalty-free, perpetual, irrevocable, non-exclusive, transferable right and license to use, reproduce, modify (to comport with the System), adapt, publish, distribute, translate, create derivative works from, distribute, perform and display such Content (in whole or part) worldwide or to incorporate it in other works in any form, media, or technology now known or later developed, without restriction or compensation. In addition, you warrant that all so-called &quot;moral rights&quot; in the Content have been waived. PersonnelPlus-Inc.com and its designees shall have the right, but not the obligation, in their sole discretion to edit, refuse to post, or remove any Content posted on the System. Without limiting the foregoing, PersonnelPlus-Inc.com and its designees shall have the right to remove any Content that violates these Terms or are otherwise objectionable. You agree to indemnify and hold PersonnelPlus-Inc.com harmless from any third party claim, damages or demand, including reasonable attorneys' fees, relating to or arising out of your violation of these Terms, your representations and warranties, or your violation of any rights of another.</p>
      <h2><span>Monitoring, etc.</span></h2>
      <p>PersonnelPlus-Inc.com is under no obligation to monitor the information residing on or transmitted via this System. However, you agree that PersonnelPlus-Inc.com may monitor the System Contents to (a) comply with any applicable laws, regulations or other government requests; (b) to operate the System properly or to protect itself and its users and Members; and (c) for such other purposes as it may deem reasonably necessary or appropriate from time to time. PersonnelPlus-Inc.com reserves the right to modify, reject or eliminate any information residing on or transmitted to its System that it, in its sole discretion, believes is unacceptable or in violation of these terms and conditions.</p>
    </blockquote>
  </div>
  <%=decorateBottom()%>
  <!-- End of Site content -->
  <!-- #INCLUDE VIRTUAL='/include/master/pageFooter.asp' -->
